---
title: "Chapter 1 - Intro to R"
author: "Enes Kemal Ergin"
date: "Wednesday, February 04, 2015"
output: pdf_document
---
# Intro to R Language
> Chapter Covers:
  - Installing R
  - Understanding the R Language
  - Running Programs
  
* Due to improvements in pretty much every area, people's need for data science has been increased, respectively. When people's need increased, need for having easily accessible and digestible ways has become increasingly challenging.

## Why Use R?
You may want to choose R becuase;
- R is specifically for statistical computing and making them visual
- It is open source
- It has opens source solutions to data analysis that supported by a large and active worldwide research community.
- R is totally free.
- Just about any type of data analysis can be done in R.
- R has great graphics capabilities.
- R has the most comprehensice and powerful feature set available.
- R can easily import data from a wide varity of sources, and write on them.

R allows you to create elegant, informative, and highly customized graphs in a simple and straightforward fashion. However, R can have a steep learning curve. You can do so much with R, but to learn all those could give you some headaches.

## Obtaining and Installing R
R is freely available from [Comprehensive R Archive Network(CRAN)](http://cran.r-project.org). Software available for Linux, Mac OS X, and Windows. 

## Working with R
R is case-sensitive, interpreted languge. You can write a command at a time and get the result without losing anytime. Command prompt (>) or running a set of commands from a source file are the ways of working with R. Most functionality of R comes from buil-in and user-created functions, and they are available by default.

Statements consist of functions and assignments. R uses the symbol <- for assignments, rather than typical = sign.

> (Continue from pg.8)
